// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfwitppieppjdlxdrixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmd2l0cHBpZXBwamRseGRyaXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTQ0NzcsImV4cCI6MjA2MzgzMDQ3N30._VSSB6r8aWouy9AdvMv7ILYJyz6OWwNGv-mESufzvDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);